---
- hosts: all
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

## In this classic way, the roles are executed first before the other tasks

  tasks:
  - name: Debug ansible fact for os_family
    ansible.builtin.debug:
      msg: "{{ ansible_facts['os_family'] }}"
  
  roles:
    - httpd_role
