---
- hosts: all
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  tasks:
  - name: Debug ansible fact for os_family
    ansible.builtin.debug:
      msg: "{{ ansible_facts['os_family'] }}"

  - name: Example for Import role (Static resue - Similar to using roles with -roles)
    import_role: 
      name: httpd_role