---

- name: Install httpd package
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Copy the newwebpage.html to the managed node
  ansible.builtin.copy:
    src: newwebpage.html
    dest: /var/www/html

- name: restart the web server service
  ansible.builtin.service:
    name: httpd
    state: restarted
  