---
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

  - name: Print os family from facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts['os_family'] }}"

  - name: Print all available facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts['distribution_major_version'] }}"

  - name: Create a group when os family is Redhat
    ansible.builtin.group:
      name: conditionalgroup1
      gid: 23101
    when: ansible_facts['os_family'] == "RedHat"
  