---
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

  - name: Print os family from facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts['os_family'] }}"

  - name: Print all available facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts['distribution_major_version'] }}"

  - name: Create a group when os family is Redhat
    ansible.builtin.group:
      name: conditinalgroup1
      gid: 23001
    when: ansible_facts['os_family'] == "RedHat"

  - name: Create a user account when os family is Redhat and OS major version is 8
    ansible.builtin.user:
      name: conditionaluser1
      uid: 23001
      group: conditionalgroup4
      comment: "Ansible test user"
      shell: /bin/bash
    when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"