---
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"
    sample_data:
      - user1
      - user2
  
  tasks:
  - name: Debug will run on webserver
    ansible.builtin.debug:
      msg: "{{ item }}"
    with_items: "{{ sample_data }}"
    vars:
      ansible_connection: ssh
      ansible_user: linuxadmin
      ansible_password: "{{ans_pwd}}"
      sample_data:
        - user1
        - user2

  - name: Shell module will run on localhost
    ansible.builtin.shell: echo "My Test file for delegation" > /var/tmp/delegation.out
    delegate_to: 127.0.0.1