---
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"
  
  tasks:
  - name: Print the dictionary keys and values
    ansible.builtin.debug:
      msg: "{{ item.key }} is {{ item.value}}"
    loop: "{{ user_data | dict2items }}"
    vars:
      user_data:
        username: "user1"
        groupname: "group1"