---
##
- hosts: localhost

  tasks:
  - name: Print all ansible facts from localhost
    ansible.builtin.debug:
      var: ansible_facts
    
  - name: Print only architecture of the localhost
    ansible.builtin.debug:
      msg: "{{ ansible_facts['architecture'] }}"