---
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"
  
  tasks:
  - name: Add several users
    ansible.builtin.user:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
      groups: "{{ item.group }}"
    loop:
      - { name: 'webuser10', group: 'wheel', state: 'present'}
      - { name: 'webuser11', group: 'wheel', state: 'absent'}