---
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"
    username:
      - webuser1
      - webadmin1
  
  tasks:
  - name: Add several users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
      groups: "wheel"
    loop: "{{ username }}"