---

- hosts: localhost

  tasks:
  - name: Install multiple packages
    ansible.builtin.apt:
      name: "{{ package_name }}"
      state: present
    vars:
      package_name:
      - mysql-server
      - nginx