---
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"
  
  tasks:
  - name: Add multiple users
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
      groups: "wheel"
    loop:
      - webuser2
      - webadmin2
      - webadmin3