---
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  tasks:
  - name: Wait until the condition is met
    ansible.builtin.shell: |
      ping -c 3 192.168.56.101
    register: output
    until: output.rc == 0
    retries: 30
    delay: 3

  - name: debug the return code
    ansible.builtin.debug:
      msg: "{{ output.rc }}"