---
## Become method su in playbook
- hosts: webserver
  
  vars:
    ansible_become: yes
    ansible_become_method: su
    ansible_become_user: root
    ansible_become_password: "{{ ans_become_pwd }}"
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ ans_pwd }}"

  tasks:
  - name: Create a group
    ansible.builtin.group:
      name: webgroup10
      gid: 21097

  - name: Create a user account
    ansible.builtin.user:
      name: webuser7
      uid: 21097
      group: webgroup10
      comment: "Ansible test user"
      shell: /bin/bash

