---
## Become method su in playbook
- hosts: webserver
  
  vars:
    ansible_become: yes
    ansible_become_method: su
    ansible_become_user: root
    ansible_become_password: "root123"
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "root123"


  tasks:
  - name: Create a group
    ansible.builtin.group:
      name: webgroup7
      gid: 21077

  - name: Create a user account
    ansible.builtin.user:
      name: webuser7
      uid: 21077
      group: webgroup7
      comment: "Ansible test user"
      shell: /bin/bash

