---
## Become method su in playbook
- hosts: webserver
  become: yes
  become_method: su
  become_user: root
  become_pass: "root123"

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "root123"
   

  tasks:
  - name: Create a group
    ansible.builtin.group:
      name: webgroup6
      gid: 21067

  - name: Create a user account
    ansible.builtin.user:
      name: webuser6
      uid: 21067
      group: webgroup6
      comment: "Ansible test user"
      shell: /bin/bash

