---
## Demo Playbook
- hosts: localhost

  tasks:
  - name: Create a user account
    ansible.builtin.user:
      name: ansibleuser1
      uid: 20001
      group: operator
      comment: "Ansible test user"
      shell: /bin/bash

  - name: Create a group
    ansible.builtin.group:
      name: ansiblegroup1
      gid: 10008
