---
- hosts: all
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  tasks:
  - name: Install httpd package
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: restart the web server service
    ansible.builtin.service:
      name: httpd
      state: restarted


  