---
- hosts: all
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  import_tasks: sometasks.yaml

  tasks:
  - name: Debug the variable Environment
    ansible.builtin.debug:
      msg: "{{ Environment }}"