---
- hosts: appserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  tasks:
    - name: Modify port number to 8080
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regex: '^Listen'
        line: Listen 8080    