---
- hosts: appserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  tasks:
    - name: Modify port number to 8080
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regex: '^Listen'
        line: Listen 8080

    - name: Restart httpd
      ansible.builtin.service:
        name: httpd
        state: restarted

    - name: Add a new entry for sudoers file
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "unixadmin  ALL=(ALL)  NOPASSWD: ALL"

    - name: Remove a entry for sudoers file
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "dsadmin	ALL=(ALL)	NOPASSWD: ALL"
        state: absent