---
### Executes task if registered variable is empty
- hosts: webserver
  become: yes
  become_method: sudo

  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  tasks:
  - name: Set a new fact 
    ansible.builtin.set_fact:
      custom_fact: file_azure
    when: cloud_type == "Azure"

  - name: AWS fact
    ansible.builtin.set_fact:
      custom_fact: file_aws
    when: cloud_type == "AWS"

  - name: Create the file
    ansible.builtin.file:
      path: /var/tmp/testdir/"{{custom_fact}}"
      state: touch
      