---
- hosts: all
  become: yes
  become_method: sudo
   
  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  tags:
    - Software

  tasks:
  - name: Install webserver
    ansible.builtin.yum:
      name: httpd
    tags:
      - webserver

  - name: Install mailserver
    ansible.builtin.yum:
      name: postfix
    tags:
      - mailserver

- hosts: all
  become: yes
  become_method: sudo
   
  vars:
    ansible_connection: ssh
    ansible_user: linuxadmin
    ansible_password: "{{ans_pwd}}"

  tags:
    - users

  tasks:
    - name: Add a user
      ansible.builtin.user:
        name: "testuser110"